### ISSUE TITLE
Curry or functional lenses ? 

### ISSUE THREAD

**Issue by decebal** [rametta/pratica#7]
I found this little library to be amazingly friendly and started using it, thank you for putting the effort.

I was wondering if you plan on adding currying or functional lenses or if you see these as good additions to the library ?

**Comment by rametta** [comment]
I think currying is great and I already support that in [get](https://github.com/rametta/pratica/blob/master/src/get.ts#L3), and [tryFind](https://github.com/rametta/pratica/blob/master/src/tryFind.ts). I'm not sure where else it would be useful since most other functions are unary.

I don't plan on adding any Lenses, I wanted to keep the lib under 1kb, but if anyone makes a PR with them and it stays under 1kb then I would consider it
